name: Deploy static content to S3

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::925173698100:role/github-actions-d4lanis
          aws-region: us-east-1

      # - name: Get variables from parameter store
      #   uses: avlima/aws-ssm-to-env@master
      #   with:
      #     aws-region: us-east-1
      #     role-to-assume: arn:aws:iam::925173698100:role/github-actions-d4lanis
      #     ssm_parameter_list: "VITE_EMAIL,VITE_FA_LINK,VITE_IG_LINK,VITE_WA_LINK"

      # - name: Print environment variables
      #   run: |
      #     echo "VITE_EMAIL: $VITE_EMAIL"
      #     echo "VITE_FA_LINK: $VITE_FA_LINK"
      #     echo "VITE_IG_LINK: $VITE_IG_LINK"
      #     echo "VITE_WA_LINK: $VITE_WA_LINK"

      # - name: Write environment variables to .env file
      #   run: |
      #     echo "VITE_EMAIL=$VITE_EMAIL" >> .env
      #     echo "VITE_FA_LINK=$VITE_FA_LINK" >> .env
      #     echo "VITE_IG_LINK=$VITE_IG_LINK" >> .env
      #     echo "VITE_WA_LINK=$VITE_WA_LINK" >> .env

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://ntech-soluciones-it-site --delete